[project]
name = "text-analysis"
version = "0.1.2"
description = "A Python package for text summarization"
authors = [{name = "Gerixmus"}]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "transformers",
    "torch"
]